name: "Hello world workflow"

on: 
  push:
    branches:
      - master
      - production
<<<<<<< HEAD
jobs:
  hello_world:
     runs-on: ubuntu-latest
     steps:
      - name: "print hello world"
        run : echo "hello world"
        
=======

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        run: echo "hello world"

>>>>>>> d174795a718c8694fceebe0a79f753540e7449cc
