name : "Multievent pipeline/workflow"
on:
    push:
        branches:
            - master
            - test
    pull_request: 
        branches:
            - master

jobs:
    on-push:
        runs-on: ubumtu-latest
        steps:
            - name: "Running on the master push"
              run: echo "Running on the master push"
    on-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"