name : "Multievent pipeline/workflow"
on:
    push:
        branches:
            - master
            - test
    pull_request: 
        branches:
            - master

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on the master push"
              run: echo "Running on the master push"
    on-pull-request:
         if: github.event_name =='pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"