name: "Multievent pipeline/workflow"
on:
  push:
    branches:
      - master
      - test
 schedule:
    - cron: "0 10 * * 2,4"
  pull_request:
    branches:
      - master
    types:
        - closed
  workflow_dispatch:

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on the master push"
        run: echo "Running on the master push"

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"
  on-pull-request-opend:
    if: github.event_name == 'pull_request' && github.event.action =='opened'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"

  on-pull-request-closed: 
    if: github.event_name == 'pull_request' && github.event.action =='closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"


  workflow_dispatch:
    if: github.event_name == 'workslow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on the workflow dispatch"
        run: echo "Running on the workflow dispatch"
  on-schedule:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on schedule"
        run: echo "Running on scheduless"

    
